name: Actions

on:
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - run: |
          curl -i -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_ACTIONS }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/itzh4ck/pr/1/merge
